import Foundation

/// User-defined tags for the videos in the library. A video can carry any
/// number of tags. Everything is persisted to `categories.json` inside the
/// library folder itself, so the metadata travels with the videos and can be
/// hand-edited or generated by scripts.
///
/// File format:
/// ```json
/// { "version": 1,
///   "tags": ["Cozy", "Nature"],
///   "videos": { "autumn-forest-cabin.mp4": ["Cozy", "Nature"] } }
/// ```
final class CategoryStore: ObservableObject {
    static let fileName = "categories.json"

    /// Every known tag, sorted for display. Includes tags with no videos yet.
    @Published private(set) var tags: [String] = []
    /// Filename (with extension) → tags. Entries for files that no longer
    /// exist are kept, so a video that's moved away and back keeps its tags.
    @Published private(set) var assignments: [String: [String]] = [:]

    private var fileURL: URL?
    private var loadedModificationDate: Date?

    // MARK: - Loading / saving

    /// Point the store at a library folder and read its `categories.json`.
    func load(folder: URL?) {
        fileURL = folder?.appendingPathComponent(Self.fileName)
        read()
    }

    /// Re-read only if the file changed on disk since we last read or wrote
    /// it — e.g. an external script regenerated it while the app is running.
    func reloadIfChanged() {
        guard let fileURL else { return }
        let onDisk = modificationDate(of: fileURL)
        if onDisk != loadedModificationDate { read() }
    }

    private func read() {
        guard let fileURL,
              let data = try? Data(contentsOf: fileURL),
              let file = try? JSONDecoder().decode(FileFormat.self, from: data) else {
            tags = []
            assignments = [:]
            loadedModificationDate = fileURL.flatMap(modificationDate)
            return
        }
        assignments = file.videos
        // Union of declared tags and anything referenced by a video, so a
        // hand-edited file can't leave orphan assignments invisible.
        var all = Set(file.tags)
        file.videos.values.forEach { all.formUnion($0) }
        tags = Self.sorted(all)
        loadedModificationDate = modificationDate(of: fileURL)
    }

    private func save() {
        guard let fileURL else { return }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let file = FileFormat(version: 1, tags: tags, videos: assignments)
        if let data = try? encoder.encode(file) {
            try? data.write(to: fileURL, options: .atomic)
            loadedModificationDate = modificationDate(of: fileURL)
        }
    }

    // MARK: - Queries

    func tags(for url: URL) -> [String] {
        assignments[url.lastPathComponent] ?? []
    }

    func has(_ tag: String, _ url: URL) -> Bool {
        tags(for: url).contains(tag)
    }

    /// Number of the given (currently present) videos carrying `tag`.
    func count(of tag: String, in videos: [URL]) -> Int {
        videos.reduce(0) { $0 + (has(tag, $1) ? 1 : 0) }
    }

    func untagged(in videos: [URL]) -> [URL] {
        videos.filter { tags(for: $0).isEmpty }
    }

    // MARK: - Mutations

    /// Add a new tag. Returns the canonical name, or nil if it was blank or
    /// already exists (case-insensitively).
    @discardableResult
    func addTag(_ name: String) -> String? {
        let trimmed = name.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }
        if let existing = tags.first(where: { $0.caseInsensitiveCompare(trimmed) == .orderedSame }) {
            return existing
        }
        tags = Self.sorted(Set(tags).union([trimmed]))
        save()
        return trimmed
    }

    func toggle(_ tag: String, for url: URL) {
        let key = url.lastPathComponent
        var current = assignments[key] ?? []
        if let i = current.firstIndex(of: tag) {
            current.remove(at: i)
        } else {
            current.append(tag)
            current = Self.sorted(Set(current))
        }
        if current.isEmpty { assignments.removeValue(forKey: key) } else { assignments[key] = current }
        if !tags.contains(tag) { tags = Self.sorted(Set(tags).union([tag])) }
        save()
    }

    func rename(_ tag: String, to newName: String) {
        let trimmed = newName.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, trimmed != tag else { return }
        // Renaming onto an existing tag merges the two.
        tags = Self.sorted(Set(tags).subtracting([tag]).union([trimmed]))
        for (key, list) in assignments where list.contains(tag) {
            assignments[key] = Self.sorted(Set(list).subtracting([tag]).union([trimmed]))
        }
        save()
    }

    /// Remove the tag everywhere. Videos left with no tags become untagged.
    func delete(_ tag: String) {
        tags.removeAll { $0 == tag }
        for (key, list) in assignments where list.contains(tag) {
            let remaining = list.filter { $0 != tag }
            if remaining.isEmpty { assignments.removeValue(forKey: key) } else { assignments[key] = remaining }
        }
        save()
    }

    // MARK: - Helpers

    private static func sorted(_ set: Set<String>) -> [String] {
        set.sorted { $0.localizedStandardCompare($1) == .orderedAscending }
    }

    private func modificationDate(of url: URL) -> Date? {
        (try? FileManager.default.attributesOfItem(atPath: url.path))?[.modificationDate] as? Date
    }

    private struct FileFormat: Codable {
        var version: Int
        var tags: [String]
        var videos: [String: [String]]
    }
}
